// src/components/Stepper/stepper.angular.component.ts
// stepper.component.ts
import { Component, Input } from '@angular/core';

export interface Step {
  id: string | number;
  label: string;
  nextStep?: string | number;
  previousStep?: string | number;
  beforeStateLoadedAction?: () => void;
}

@Component({
  selector: 'app-stepper',
  standalone: true,
  template: `
    <div>
      <div>{{ currentStep.label }}</div>
      <ng-content></ng-content>
    </div>
  `,
})
export class StepperComponent {
  @Input() initialStepId!: Step['id'];
  @Input() steps: Step[] = [];

  currentStepId!: Step['id'];

  ngOnInit() {
    if (!this.initialStepId) {
      throw new Error('initialStepId input is required');
    }
    this.currentStepId = this.initialStepId;
  }

  get currentStep(): Step {
    const step = this.steps.find((s) => s.id === this.currentStepId);
    if (!step) {
      throw new Error(`Active step id ${this.currentStepId} not found in steps`);
    }
    return step;
  }

  changeStep(newStepId: Step['id']) {
    this.currentStepId = newStepId;
    this.currentStep.beforeStateLoadedAction?.();
  }

  goToNextStep() {
    if (!this.currentStep.nextStep) {
      throw new Error("You are on the last step, can't go further");
    }
    this.changeStep(this.currentStep.nextStep);
  }

  goToPreviousStep() {
    if (!this.currentStep.previousStep) {
      throw new Error("You are on the first step, can't go back");
    }
    this.changeStep(this.currentStep.previousStep);
  }
}

// src/components/Stepper/Stepper.vue
<template>
    <div>
        <div>{{ currentStep.label }}</div>
        <slot
          :goToNextStep="goToNextStep"
          :goToPreviousStep="goToPreviousStep"
          :changeStep="changeStep"
        />
    </div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue"

import type { Step } from "./stepper.model"


interface IProps {
    initialStepId: Step['id']
    steps: Step[]
}

const props = defineProps<IProps>();

const currentStepId = ref(props.initialStepId)

const currentStep = computed<Step>(() => {
    const activeStep = props.steps.find((step) => step.id === currentStepId.value)

    if(!activeStep) {
        throw new Error(`Make sure you passed currect step ids, active step id ${currentStepId.value} not found in defined steps`)
    }

    return activeStep
})

const changeStep = (newStepId: Step['id']) => {
    currentStepId.value = newStepId
    currentStep.value.beforeStateLoadedAction?.()
}

const goToNextStep = () => {
    if(!currentStep.value.nextStep) {
        throw new Error('You are on the last step, can\'t go futher')
    }
    changeStep(currentStep.value.nextStep)
}

const goToPreviousStep = () => {
    if(!currentStep.value.previousStep) {
        throw new Error('You are on the first step, can\'t go back')
    }
    changeStep(currentStep.value.previousStep)
}
</script>
