// src/components/Form/stepperExample.angular.component.ts
// form-stepper.component.ts
import { Component, OnInit } from '@angular/core';
import { Step } from '../stepper/stepper.model';
import { AvailableFormStates, FormStates } from './form-states.model'; // Extract enum/type for clarity

@Component({
  selector: 'app-form-stepper',
  standalone: true,
  imports: [
    StepperComponent,
    StartStepComponent,
    NextStepComponent,
    LastStepComponent,
    CommonModule,
  ],
  template: `
    <ng-container *ngIf="currentFormState.name !== AvailableFormStates.LOADING; else loadingTemplate">
      <app-stepper
        [steps]="steps"
        [initialStepId]="steps[0].id"
        #stepper
      >
        <ng-container *ngIf="currentFormState.name === AvailableFormStates.START">
          <app-start-step (save)="saveStartInfo($event.name, $event.surname)"></app-start-step>
        </ng-container>
        <ng-container *ngIf="currentFormState.name === AvailableFormStates.NEXT">
          <app-next-step [fullName]="currentFormState.fullName"></app-next-step>
        </ng-container>
        <ng-container *ngIf="currentFormState.name === AvailableFormStates.LAST">
          <app-last-step></app-last-step>
        </ng-container>
        <button (click)="stepper.goToPreviousStep()">
          Wstecz
        </button>
        <button (click)="stepper.goToNextStep()">
          Dalej
        </button>
      </app-stepper>
    </ng-container>
    <ng-template #loadingTemplate>
      <div>Ładowanko</div>
    </ng-template>
  `,
})
export class FormStepperComponent implements OnInit {
  AvailableFormStates = AvailableFormStates;

  currentFormState: FormStates = {
    name: AvailableFormStates.LOADING,
  };

  form = {
    name: '',
    surname: '',
  };

  steps: Step[] = [
    {
      id: 'start',
      label: 'Wpisz dane',
      nextStep: 'next',
      beforeStateLoadedAction: () => {
        this.currentFormState = { name: AvailableFormStates.START };
      },
    },
    {
      id: 'next',
      label: 'Upewnij się o danych',
      nextStep: 'koniec',
      previousStep: 'start',
      beforeStateLoadedAction: () => {
        this.currentFormState = {
          name: AvailableFormStates.NEXT,
          fullName: `${this.form.name} ${this.form.surname}`,
        };
      },
    },
    {
      id: 'koniec',
      label: 'Zobacz dane',
      previousStep: 'next',
      beforeStateLoadedAction: () => {
        this.currentFormState = { name: AvailableFormStates.LAST };
      },
    },
  ];

  ngOnInit() {
    // Simulate initial loading state then switch to start step
    setTimeout(() => {
      const startStep = this.steps.find((s) => s.id === 'start');
      if (startStep && startStep.beforeStateLoadedAction) {
        startStep.beforeStateLoadedAction();
      }
    }, 2000);
  }

  saveStartInfo(name: string, surname: string) {
    this.form = { name, surname };
  }
}

// src/components/Form/StepperExample.vue
<template>
    <Stepper :steps="steps" :initial-step-id="steps[0].id" v-if="currentFormState.name !== AvailableFormStates.LOADING">
        <template #default="actions">
            <StartStep
              v-if="currentFormState.name === AvailableFormStates.START"
              @save="saveStartInfo"
            />
            <NextStep
              v-if="currentFormState.name === AvailableFormStates.NEXT"
              :full-name="currentFormState.fullName"
            />
            <LastStep v-if="currentFormState.name === AvailableFormStates.LAST"/>
            <button @click="actions.goToPreviousStep()">
                Wstecz
            </button>
            <button @click="actions.goToNextStep()">
                Dalej
            </button>
        </template>
    </Stepper>
    <div v-else-if="currentFormState.name === AvailableFormStates.LOADING">
        Ładowanko
    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

import Stepper from '../Stepper/Stepper.vue';
import type { Step } from '../Stepper/stepper.model'

import StartStep from './StartStep.vue';
import NextStep from './NextStep.vue';
import LastStep from './LastStep.vue';

const form = ref({
    name: '',
    surname: '',
})

setTimeout(() => {
    currentFormState.value = {
        name: AvailableFormStates.START
    }
}, 2000)

const steps: Step[] = [
    {
        id: 'start',
        label: "Wpisz dane",
        nextStep: 'next',
        beforeStateLoadedAction: () => {
            currentFormState.value = {
                name: AvailableFormStates.START
            }
        }
    },
    {
        id: 'next',
        label: "Upewnij się o danych",
        nextStep: 'koniec',
        previousStep: 'start',
        beforeStateLoadedAction: () => {
            currentFormState.value = {
                name: AvailableFormStates.NEXT,
                fullName: `${form.value.name} ${form.value.surname}`
            }
        }
    },
    {
        id: 'koniec',
        label: "Zobacz dane",
        previousStep: 'next',
        beforeStateLoadedAction: () => {
            currentFormState.value = {
                name: AvailableFormStates.LAST
            }
        }
    },
]

enum AvailableFormStates {
    LOADING = "LOADING",
    START = "START",
    NEXT = "NEXT",
    LAST = "LAST"
}

type FormStates = {
    name: AvailableFormStates.LOADING
} | {
    name: AvailableFormStates.START,
} | {
    name: AvailableFormStates.NEXT,
    fullName: string,
} | {
    name: AvailableFormStates.LAST
}

const currentFormState = ref<FormStates>({
    name: AvailableFormStates.LOADING
})

const saveStartInfo = (name: string, surname: string) => {
    form.value = {
        name,
        surname,
    }
}
</script>
